package thesisfinal;

import javax.swing.*;
import java.awt.*;
import java.io.FileReader;
import java.io.IOException;
import java.io.LineNumberReader;
import java.util.Random;

import static thesisfinal.DhakaSimFrame.car_following_model;
import static thesisfinal.DhakaSimFrame.seed;

public class OptionPanel extends javax.swing.JPanel {

    private DhakaSimFrame dhakaSimFrame;

    /**
     * Creates new form OptionList
     */
    public OptionPanel(DhakaSimFrame dhakaSimFrame) {
        this.dhakaSimFrame = dhakaSimFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1250, 700));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        jLabel1.setText("DhakaSim");

        jTextField1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextField1.setText("" + DhakaSimFrame.simulationSpeed);

        jTextField2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextField2.setText("" + DhakaSimFrame.simulationEndTime);

        jTextField3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextField3.setText("" + seed);

        jTextField4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextField4.setText("" + DhakaSimFrame.TRACE_MODE);

        jTextField5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextField5.setText("" + DhakaSimFrame.pixelPerMeter);

        jTextField6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextField6.setText("" + DhakaSimFrame.encounterPerAccident);

        jTextField7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextField7.setText("" + DhakaSimFrame.stripWidth);

        jTextField8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextField8.setText("" + DhakaSimFrame.footpathStripWidth);

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("Simulation Speed:");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("Simulation End Time:");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("Random Seed:");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setText("Trace Mode:");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("Pixel Per Meter:");

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel7.setText("Probability of Accident:");

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel8.setText("Strip Width:");

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel9.setText("Footpath Strip Width:");

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel10.setText("Pedestrian:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jRadioButton1.setSelected(DhakaSimFrame.pedestrianMode);
        jRadioButton1.setText("On");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jRadioButton2.setSelected(!DhakaSimFrame.pedestrianMode);
        jRadioButton2.setText("Off");

        jButton1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jButton1.setText("Start Simulation");
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel11.setText("MaximumSpeed:");

        jTextField9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextField9.setText("" + DhakaSimFrame.maximumSpeed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(438, 438, 438)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel2)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jLabel4)
                                                                .addComponent(jLabel5)
                                                                .addComponent(jLabel6)
                                                                .addComponent(jLabel7)
                                                                .addComponent(jLabel8)
                                                                .addComponent(jLabel9))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                                .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel11)
                                                                .addComponent(jLabel10))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jRadioButton1)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jRadioButton2))
                                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(109, 109, 109))))
                                .addContainerGap(444, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jRadioButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DhakaSimFrame.simulationSpeed = Integer.parseInt(jTextField1.getText());
        DhakaSimFrame.simulationEndTime = Integer.parseInt(jTextField2.getText());
        seed = Integer.parseInt(jTextField3.getText());
        System.out.println("Seed: " + seed);
        System.out.println("CF Model: " + car_following_model);
        DhakaSimFrame.random = seed < 0 ? new Random() : new Random(seed);
        DhakaSimFrame.TRACE_MODE = Boolean.parseBoolean(jTextField4.getText());
        DhakaSimFrame.pixelPerMeter = Double.parseDouble(jTextField5.getText());
        double value = Double.parseDouble(jTextField6.getText());
        if (value < 1) {
            value = 100 / value;
        } else {
            value = 100 - value + 1;
        }
        DhakaSimFrame.encounterPerAccident = value;
        DhakaSimFrame.stripWidth = Double.parseDouble(jTextField7.getText());
        DhakaSimFrame.footpathStripWidth = Double.parseDouble(jTextField8.getText());
        DhakaSimFrame.maximumSpeed = Double.parseDouble(jTextField9.getText()) * 1000 / 3600; // m/s
        DhakaSimFrame.maximumSpeed = Utilities.precision2(DhakaSimFrame.maximumSpeed);
        DhakaSimFrame.pedestrianMode = jRadioButton1.isSelected();
        {
            DhakaSimFrame.pixelPerFootpathStrip = DhakaSimFrame.pixelPerMeter * DhakaSimFrame.footpathStripWidth;
            DhakaSimFrame.pixelPerStrip = DhakaSimFrame.pixelPerMeter * DhakaSimFrame.stripWidth;
        }
        DhakaSimPanel dhakaSimPanel = new DhakaSimPanel(dhakaSimFrame);
        JSlider jSlider = new JSlider(JSlider.VERTICAL, 0, 100, 30);
        JSlider showProgressSlider = new JSlider(JSlider.HORIZONTAL, 1, DhakaSimFrame.simulationEndTime, 1);
        JSlider changeTraceSlider = new JSlider(JSlider.HORIZONTAL, 1, DhakaSimFrame.simulationEndTime, 1);
        DhakaSimFrame.showProgressSlider = showProgressSlider;

        showProgressSlider.setMinorTickSpacing(10);
        showProgressSlider.setMajorTickSpacing(50);
        showProgressSlider.setPaintTicks(true);

        changeTraceSlider.setMinorTickSpacing(10);
        changeTraceSlider.setMajorTickSpacing(50);
        changeTraceSlider.setPaintTicks(true);

        jSlider.addChangeListener(ce -> {
            JSlider tmp = (JSlider) ce.getSource();
            double scaleValue = Math.max(0.00001, tmp.getValue() / 100.0);
            dhakaSimPanel.setScale(scaleValue);
            if (DhakaSimFrame.DEBUG_MODE) {
                System.out.println("Scale Value: " + scaleValue);
            }
        });

        changeTraceSlider.addChangeListener(ce -> {
            JSlider temp = (JSlider)ce.getSource();
            if (DhakaSimFrame.TRACE_MODE) {
                DhakaSimFrame.simulationStep = temp.getValue();
                LineNumberReader traceReader = dhakaSimPanel.getTraceReader();
                try {
                    traceReader.close();
                    traceReader = new LineNumberReader(new FileReader("trace.txt"));
                    dhakaSimPanel.setTraceReader(traceReader);
                    int lineNo = DhakaSimFrame.simulationStepLineNos.get(temp.getValue() - 1);
                    for (int i = 1; i < lineNo; i++) {
                        traceReader.readLine();
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        dhakaSimFrame.getContentPane().removeAll();
        dhakaSimFrame.getContentPane().add(jSlider, BorderLayout.EAST);
        dhakaSimFrame.getContentPane().add(showProgressSlider, BorderLayout.SOUTH);
        if (DhakaSimFrame.TRACE_MODE) {
            dhakaSimFrame.getContentPane().add(changeTraceSlider, BorderLayout.NORTH);
        }
        dhakaSimFrame.getContentPane().add(dhakaSimPanel, BorderLayout.CENTER);
        dhakaSimFrame.getContentPane().addMouseWheelListener(dhakaSimPanel);
        dhakaSimFrame.repaint();
        dhakaSimFrame.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
